### ISSUE TITLE
Normalize polarization vectors

### ISSUE THREAD

**Issue by js216** [ograsdijk/CeNTREX-TlF#12]
If a user specifies a polarization like `[0,1,1]`, then the Rabi rate for this transition will be off by √2. Mistakes like that can be avoided if the program were to automatically normalize the polarization vectors, or report an error when a vector is not normalized.

**Comment by ograsdijk** [comment]
added in ad1fb793c1147be48cfe49f60eaae97df7616929, now normalizes the polarization to length 1 by default with `normalize_pol = True`
