### ISSUE TITLE
1D scanning over multiple parameters

### ISSUE THREAD

**Issue by js216** [ograsdijk/CeNTREX-TlF#14]
`setup_problem_parameter_scan()` supports scanning over multiple parameters, such that each parameter corresponds to its own dimension. Thus scanning over two parameters (each with a given 1D list of values) returns a 2D array of results.

Sometimes, however, it is useful to change two parameters at the same time: for instance, increase laser beam width and thus reduce the maximum Rabi rate. A 2D scan over beam width and Rabi rate would yield this information, but would take longer than needed; all that's needed is a 1D scan over 'zipped' pairs `(Ωl0, σ)`.

**Comment by ograsdijk** [comment]
Implemented in 9c4628f41f895cfbc4208e86bb6f5e474e407556, function `setup_parameter_scan_zipped(odePar, parameters, values)`, where `values` is a list of lists or arrays which are zipped.

**Comment by js216** [comment]
The function `setup_parameter_scan_zipped()` may need to be listed in `__all__` of `lindblad/utils_julia.py` ?

**Comment by ograsdijk** [comment]
Fixed
