### ISSUE TITLE
Ode Parameter Bug

### ISSUE THREAD

**Issue by nclayburn** [ograsdijk/CeNTREX-TlF#15]
It seems like the ode parameters can not end in a list. Perhaps because then it is missing a terminal closing bracket. This problem arises when using a multipass list parameter as the final entry of odepars. A work around is moving the list parameters such that they are not last.

   # Code
    odepars = centrex.lindblad.odeParameters(
    Ωl = "Ωl0 * phase_modulation(t, β, ωphase) * multipass_2d_intensity(vz*t, y0+vy*t, ampl, xlocs, ylocs, σzlaser, σylaser)",
    Ωl0     = 1*syspars.Γ,    # Rabi frequency of the laser [rad/s]
    δl      = 0,              # detuning of the laser [rad/s]
    σzlaser = 0.002*np.sqrt(2),          # laser horizontal width [m]
    σylaser = 0.002*np.sqrt(2),          # laser vertical width [m]
     # laser multipass parameters
    ampl    = [np.sqrt(0.944**n) for n in range(13)],
    xlocs   = [n*0.003+0.008 for n in centrex.utils.light.multipass_prism_order(13)],
             
    # laser phase modulation
    ωphase = syspars.Γ,       # laser phase modulation frequency [rad/s]
    β      = 3.8,             # laser phase modulation depth [rad]

    # laser polarization switching
    ωp = 2*np.pi*1.56e6,           # polarization switching frequency [rad/s]
    φp = 0.0,                 # polarization switching phase [rad]
    Pl  = "sin(ωp*t + φp)",
    Plz = "Pl>0",
    Plx = "Pl<=0",
    
    # molecules
    y0 = 0,                   # molecule start y position [m]
    vz = 184,                 # longitudinal molecular velocity [m/s]
    vy = 1,                   # molecule vy [m/s]
    
    ylocs   = 13*[0.0],)

Will fail when doing parameter scans with error:

      JuliaError: Exception 'syntax: missing separator in array expression' occurred while calling julia code:

    @everywhere params = $params
    @everywhere function prob_func(prob, i, repeat)
        remake(prob, p = [params[i,1], 0, 0.0028284271247461905, 0.0028284271247461905, [1.0, 0.9715966241192895,params[i,3], 0.9171872131686093,params[i,2], 0.865824729231167, 0.8412323839999999, 0.8173385443942217, 0.7941233704959998, 0.7715675859081452, 0.7496524617482239, 0.728359801097289, 0.7076719238903233], [0.011, 0.044000000000000004, 0.017, 0.038, 0.023, 0.032, 0.029, 0.026000000000000002, 0.035, 0.02, 0.041, 0.014, 0.047], 9801769.079200154, 3.8, 9801769.079200154, 0.0, 0, 184, 1, [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0])
    end

**Comment by ograsdijk** [comment]
Fixed in 30dd57deb0405d2db72c6a70aeb60f9f9e7932fe
