### ISSUE TITLE
Automatically determine the 'main' states of a transition

### ISSUE THREAD

**Issue by js216** [ograsdijk/CeNTREX-TlF#4]
When a transition is driven between two manifolds of states, more than one hyperfine sublevels in each manifold may be involved. However, the code requires the user to identify two 'main' levels for some reason beyond my understanding. This is not a physical concept, and the program should find the main states automatically and behind the scenes.

**Comment by ograsdijk** [comment]
added in 6497be89d71706d3cc40f004b9f1956755c8ab11
