### ISSUE TITLE
Identify states using quantum numbers instead of numerical index

### ISSUE THREAD

**Issue by js216** [ograsdijk/CeNTREX-TlF#6]
At several points in the simulation process, the user may want to select one or more particular states, and at present one has to know what order these states are in `QN`. For example, to compact all J=2 states when there are J=0 states present, you write:

        slice_compact = np.s_[4:24]

Since Julia and Python start indexing at 1 and 0, resp., it's easy to make off-by-1 mistakes. It would be much more readable to directly specify the quantum numbers of states the user wishes to compact. This would be esp. helpful when the simulation is changed by adding or removing additional states, which may change the numbering.

This also applies to `lindblad.setup_state_integral_calculation` and `utils.generate_population_states` and potentially other functions.

**Comment by ograsdijk** [comment]
partially implemented in d7f69e4f39ecaa3a8e05db19ac58efebe33260f0, can now supply `qn_compact` to `generate_total_symbolic_hamiltonian` and `collapse_matrices`  to use quantum numbers to compact the system, where:
```Python
qn_compact = [{'J':2, 'F': 1, 'electronic state': 'X'},
                         {'J':2, 'F': 2, 'electronic state': 'X'},
                         {'J':2, 'F': 3, 'electronic state': 'X'}]
```
Still need to figure out a nice way to do this for `lindblad.setup_state_integral_calculation` and `utils.generate_population_states`, given you'd want to be able to specify specific combinations some J, F1 and maybe multiple F per F1.
